version: '3.3'

services:
  mongo:
      image: mongo
      ports:
        - "27017:27017"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: mern-backend
    container_name: mern-backend
    command: npm start
    volumes:
      - ./backend/:/usr/backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: mern-frontend
    container_name: mern-frontend
    command: npm start
    volumes:
      - ./frontend/:/usr/frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
